alias grep='grep --color=auto'
alias o='less -R'
alias v='vim'
alias f='~/tools/find_path_param.sh'
alias l='ls -lah --color=auto'
alias lg='ls -lah | grep'
alias wbrc='vim ~/.bashrc'
alias rbrc='source ~/.bashrc'
alias wvrc='vim ~/.vimrc'
alias wbac='vim ~/.bash_aliases'
alias t='tmux'
alias tl='tmux ls'
alias ts='tmux new -s'
alias ta='tmux attach -t'
alias tk='tmux kill-session -t'
alias mv='mv -i'
alias cp='cp -i'
alias cc='cc -Wall'
alias cd..='cd ..'
alias cd...='cd ../..'
alias cd....='cd ../../..'
alias ..='cd ..'
alias ...='cd ../..'
alias p='python3'
