# Common Aliases
alias v='vim'
alias o='less'
alias l='ls -lah'
alias mv='mv -i'
alias cp='cp -i'
alias t='tmux'
alias ta='tmux attach-session -t'
alias tl='tmux ls'
alias ts='tmux new -s'
alias tk='tmux kill-session -t'
alias ..='cd ..'
alias cd..='cd ..'
alias cd...='cd ../..'
alias wbrc='vim $HOME/.bashrc'
alias rbrc='source $HOME/.bashrc'
alias wvrc='vim $HOME/.vimrc'
alias cc='cc -Wall'
