alias grep='grep --color=auto'
alias o='less -R'
alias v='vim'
alias f='~/tools/find_path_param.sh'
alias l='ls -lah --color=auto'
alias lg='ls -lah | grep'
alias wbrc='v ~/.bashrc'
alias rbrc='source ~/.bashrc'
alias wvrc='v ~/.vimrc'
alias wbac='v ~/.bash_aliases'
alias t='tmux'
alias tl='t ls'
alias ts='t new -s'
alias ta='t attach-session -t'
alias tk='t kill-session -t'
alias mv='mv -i'
alias cp='cp -i'
alias cc='cc -Wall'
alias cd..='cd ..'
alias cd...='cd ../..'
alias cd....='cd ../../..'
alias ..='cd ..'
alias ...='cd ../..'
alias p='python3'
